name: Build and Deploy

# 언제(어떤 이벤트 때) 이 워크플로우를 실행할지 정의합니다.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) 소스 체크아웃
      - uses: actions/checkout@v3
      
      # 2) 필요한 의존성 설치
      - name: Install dependencies
        run: |
          # 예시: Node.js 프로젝트라면
          npm install
       
      # 3) 빌드
      - name: Build
        run: |
          npm run build
          
      # (빌드 결과물을 어디에 만들어두는지는 npm 스크립트 설정에 따라 달라집니다)
  
  deploy:
    needs: [build]  # build job이 끝나야 deploy job을 실행
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 배포용 액션 사용(아래는 예시)
      - name: Deploy with GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # GitHub의 자동 생성 토큰
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          # 배포할 폴더 (앞에서 npm build 결과가 들어있는 폴더)
          publish_dir: ./dist
